[build]
command = 'hugo --qc --minify'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.148.2'
HUGO_ENABLEGITINFO = "true"
# This is the important one for Hugo’s Dart Sass integration:
HUGO_DART_SASS_PATH = "node_modules/.bin/sass"


[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
